error-mapping:
  path: "."
  filename: application-local

log:
  startup-phrase:
    title:
      value: . ACCESS GATEWAY SERVICE .
      font: digital
    message:
      value: . GOPHER-GUARD-SVC 2 .
      font: digital
  logging-level: "DEBUG"
  values:
    product: "lm-access"
    application: "Go base"
    service-name: "go_base"
    channel: "TBD"
    language: "Go"
    thread: "N/A"
    log-level:
      debug: "DEBUG"
      informative: "INFO"
      warning: "WARNING"
      error: "ERROR"
      fatal: "FATAL"

error-map:
  - internal-code: 10
    external-http-status: 500
    external-message: "Internal Server Error"
  - internal-code: 30
    external-http-status: 400
    external-message: "The parameter provided is empty"
  - internal-code: 62
    external-http-status: 400
    external-message: "Bad Request"
  - internal-code: 200
    external-http-status: 504
    external-message: "Waiting time deadline exceeded."
  - internal-code: 201
    external-http-status: 400
    external-message: "Gateway redirection error"
  - internal-code: 220
    external-http-status: 403
    external-message: "Authorization header is empty"
  - internal-code: 221
    external-http-status: 403
    external-message: "Authorization header is incomplete"
  - internal-code: 250
    external-http-status: 403
    external-message: "Introspected token is invalid"
  - internal-code: 260
    external-http-status: 403
    external-message: "Token payload problems"
  - internal-code: 261
    external-http-status: 403
    external-message: "No access key inside token payload"
  - internal-code: 262
    external-http-status: 403
    external-message: "No client id inside token payload"
  - internal-code: 263
    external-http-status: 403
    external-message: "No subject inside token payload"
  - internal-code: 264
    external-http-status: 403
    external-message: "Security: no scope inside token payload"
  - internal-code: 500
    external-http-status: 400
    external-message: "Field: the requested field is missing or empty"
  - internal-code: 501
    external-http-status: 400
    external-message: "Field: the field does not match the expected value"
  - internal-code: 950
    external-http-status: 500
    external-message: "The needed implementation is incomplete"
  - internal-code: 999
    external-http-status: 500
    external-message: "Internal Server Error"